shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.catppuccin_mocha-zsh-syntax-highlighting]
github = "catppuccin/zsh-syntax-highlighting"
