[general]
import = [ "./catppuccin/catppuccin-mocha.toml" ]

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15
